apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: queue
spec:
  # number of Pods should exist at all times.
   replicas: 3
   selector:
     matchLabels: # we need this in case of replicaset/deployments
      app: queue
   template: # template for pod
    metadata:
      name: queue # optional when you put in replica set/deployment
      labels:
        app: queue
    spec:
      containers:
      - name: queue
        #image: richardchesterwood/k8s-fleetman-queue:release1
        image: richardchesterwood/k8s-fleetman-queue:release2
        resources:
          requests: # *** specifying requests is a good practice ***
            memory: 2100Mi # 1Mi = 1024Ki   1Ki = 1024bytes
                          # 1M = 1000K   1K = 1000bytes