apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: queue
spec:
  # number of Pods should exist at all times.
   replicas: 1
   selector:
     matchLabels: # we need this in case of replicaset/deployments
      app: queue
   template: # template for pod
    metadata:
      name: queue # optional when you put in replica set/deployment
      labels:
        app: queue
    spec:
      containers:
      - name: queue
        #image: richardchesterwood/k8s-fleetman-queue:release1
        #image: richardchesterwood/k8s-fleetman-queue:release2
        image: richardchesterwood/k8s-fleetman-queue:resources  # this has initial memory or Xmx50m set for better performance and to occupy less java process memory which in turn optimizes the pod/container memory
        resources:
          requests: # *** specifying requests is a good practice ***
            memory: 300Mi # this is set based on analysis using kubectl top pod , and decided this to be good memory value to be set
            cpu: 100m

---

apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: position-simulator
spec:
  # number of Pods should exist at all times.
   replicas: 1
   selector:
     matchLabels: # we need this in case of replicaset/deployments
      app: position-simulator
   template: # template for pod
    metadata:
      name: position-simulator # optional when you put in replica set/deployment
      labels:
        app: position-simulator
    spec:
      containers:
      - name: position-simulator
        #image: richardchesterwood/k8s-fleetman-position-simulator:release1
        #image: richardchesterwood/k8s-fleetman-position-simulator:release2
        image: richardchesterwood/k8s-fleetman-position-simulator:resources  # this has initial memory or Xmx50m set for better performance
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
        resources:
          requests: # *** specifying requests is a good practice ***
            memory: 200Mi # this is set based on analysis using kubectl top pod , and decided this to be good memory value to be set
            cpu: 50m # this is set based on analysis using kubectl top pod , and decided this to be good cpu value to be set

---

apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: position-tracker
spec:
  # number of Pods should exist at all times.
   replicas: 1
   selector:
     matchLabels: # we need this in case of replicaset/deployments
      app: position-tracker
   template: # template for pod
    metadata:
      name: position-tracker # optional when you put in replica set/deployment
      labels:
        app: position-tracker
    spec:
      containers:
      - name: position-tracker
        #image: richardchesterwood/k8s-fleetman-position-tracker:release1
        #image: richardchesterwood/k8s-fleetman-position-tracker:release2
        #image: richardchesterwood/k8s-fleetman-position-tracker:release3
        image: richardchesterwood/k8s-fleetman-position-tracker:resources  # this has initial memory or Xmx50m set for better performance
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
        resources:
          requests: # *** specifying requests is a good practice ***
            memory: 250Mi # this is set based on analysis using kubectl top pod , and decided this to be good memory value to be set
            cpu: 50m # this is set based on analysis using kubectl top pod , and decided this to be good cpu value to be set

---

apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: api-gateway
spec:
  # number of Pods should exist at all times.
   replicas: 1
   selector:
     matchLabels: # we need this in case of replicaset/deployments
      app: api-gateway
   template: # template for pod
    metadata:
      name: api-gateway # optional when you put in replica set/deployment
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        #image: richardchesterwood/k8s-fleetman-api-gateway:release1
        #image: richardchesterwood/k8s-fleetman-api-gateway:release2
        image: richardchesterwood/k8s-fleetman-api-gateway:resources  # this has initial memory or Xmx50m set for better performance
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
        resources:
          requests: # *** specifying requests is a good practice ***
            memory: 300Mi  # this is set based on analysis using kubectl top pod , and decided this to be good memory value to be set
            cpu: 50m # this is set based on analysis using kubectl top pod , and decided this to be good cpu value to be set

---

apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: webapp
spec:
  # number of Pods should exist at all times.
   replicas: 1
   selector:
     matchLabels: # we need this in case of replicaset/deployments
      app: webapp
   template: # template for pod
    metadata:
      name: webapp # optional when you put in replica set/deployment
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        #image: richardchesterwood/k8s-fleetman-webapp-angular:release1
        image: richardchesterwood/k8s-fleetman-webapp-angular:release2
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
        resources:
          requests: # *** specifying requests is a good practice ***
            memory: 100Mi  # this is set based on analysis using kubectl top pod , and decided this to be good memory value to be set
            cpu: 50m # this is set based on analysis using kubectl top pod , and decided this to be good cpu value to be set