apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: mongodb
spec:
  # number of Pods should exist at all times.
   replicas: 1
   selector:
     matchLabels: # we need this in case of replicaset/deployments
      app: mongodb
   template: # template for pod
    metadata:
      name: mongodb # optional when you put in replica set/deployment
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:3.6.5-jessie
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
        resources:
          requests: # *** specifying requests is a good practice ***
            memory: 500Mi # this is set based on analysis using kubectl top pod , and decided this to be good memory value to be set
            cpu: 500m # this is set based on analysis using kubectl top pod , and decided this to be good cpu value to be set
      volumes:
        - name: mongo-persistent-storage
          # pointer to the configuration of HOW we want the mount to be implemented
          persistentVolumeClaim: # this gives advantage of being being adaptable to any cloud storage and we don't need to specify and directory structures
            claimName: mongo-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
spec:
  selector:
    app: mongodb
  ports:
    - name: mongoport
      port: 27017
  type: ClusterIP