apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: webapp
spec:
  # number of Pods should exist at all times.
   replicas: 2
   #minReadySeconds: 30
   selector:
     matchLabels: # we need this in case of replicaset/deployments
      app: webapp
   template: # template for pod
    metadata:
      name: webapp # optional when you put in replica set/deployment
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1