apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: queue
spec:
  # number of Pods should exist at all times.
   replicas: 2
   selector:
     matchLabels: # we need this in case of replicaset/deployments
      app: queue
   template: # template for pod
    metadata:
      name: queue # optional when you put in replica set/deployment
      labels:
        app: queue
    spec:
      containers:
      - name: queue
        #image: richardchesterwood/k8s-fleetman-queue:release1
        image: richardchesterwood/k8s-fleetman-queue:release2
        resources:
          requests: # *** specifying requests is a good practice ***
            memory: 4Mi # change from 300Mi to 4Mi , which is the lowest you can specify for a limit
            cpu: 0.1      # or 100mi
          limits: # *** specifying requests is a optional practice ***
            memory: 4Mi  # change from 500Mi to 4Mi , which is the lowest you can specify for a limit
            cpu: 0.1
